cache:
  mount:
    - /drone/node_modules

pipeline:
  tests:
    image: node
    commands:
      - mkdir -p /drone/node_modules
      - cp -a /drone/node_modules ./
      - rm -rf /drone/node_modules
      - npm install
      - npm install -g codecov
      - npm run test-cov
      - codecov -t ${UPLOAD_TOKEN}
      - cp -a ./node_modules /drone
    when:
      event: 
        - push 
        - pull_request

  deploy:
    image: appleboy/drone-ssh
    host: studynator.me
    user: root
    username: root
    port: 22
    key: ${SSH_KEY}
    when:
      event: push
      branch: master
    script:
      - cd ~/PU78
      - git checkout master
      - git pull
      - git checkout server
      - git merge master -m "Merge"
      - npm install
      - npm run build  
