pipeline:
  deployment:
    image: appleboy/drone-ssh
    host: studynator.me
    user: root
    key_path: ~/.ssh/id_rsa
    port: 22
    when:
      event: push
      branch: master
    script:
      - cd ~/PU78
      - git checkout master
      - git pull
      - git checkout server
      - git merge master -m "Merge"
      - cd ~/PU78/client
      - npm install
      - npm build  
      - cd ~/PU78/server
      - npm install