pipeline:
  tests:
    image: node
    commands:
      - cd client
      - npm install
      - npm install -g codecov
      - npm test
      - codecov -t ${UPLOAD_TOKEN}
    when:
      event: push
      branch: master

  deploy:
    image: appleboy/drone-ssh
    host: studynator.me
    user: root
    username: root
    port: 22
    key: ${SSH_KEY}
    when:
      event: push
      branch: master
    script:
      - echo ${TEST}
      - cd ~/PU78
      - git checkout master
      - git pull
      - git checkout server
      - git merge master -m "Merge"
      - cd ~/PU78/client
      - npm install
      - npm run build  
      - cd ~/PU78/server
      - npm install
